
# parsingTable.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C4F0829E1408D95643A99CCC32A50CC8'
    
_lr_action_items = {'RPAREN':([2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[-1,-4,25,-9,-13,-10,-11,-7,-12,-14,-8,-6,-5,-2,-3,]),'DIVIDE':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[5,-1,-4,5,-9,5,-10,5,5,5,5,5,5,-5,-2,-3,]),'MINUS':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[12,-1,-4,12,-9,12,-10,12,-7,12,12,-8,12,-5,-2,-3,]),'MINUSEQUAL':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[6,-1,-4,6,-9,6,-10,6,-7,6,6,-8,6,-5,-2,-3,]),'NUMBER':([0,3,5,6,7,8,9,10,11,12,13,15,],[2,2,2,2,2,2,2,2,2,2,2,26,]),'TIMES':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[7,-1,-4,7,-9,7,-10,7,7,7,7,7,7,-5,-2,-3,]),'PLUSEQUAL':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[8,-1,-4,8,-9,8,-10,8,-7,8,8,-8,8,-5,-2,-3,]),'PLUS':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[9,-1,-4,9,-9,9,-10,9,-7,9,9,-8,9,-5,-2,-3,]),'ATTR':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[13,-1,15,13,-9,13,-10,13,-7,13,13,-8,13,-5,-2,-3,]),'LPAREN':([0,3,5,6,7,8,9,10,11,12,13,],[3,3,3,3,3,3,3,3,3,3,3,]),'BOOL':([15,],[27,]),'EXP':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[10,-1,-4,10,-9,10,-10,10,-7,10,10,-8,10,-5,-2,-3,]),'TIMESEQUAL':([1,2,4,14,16,17,18,19,20,21,22,23,24,25,26,27,],[11,-1,-4,11,-9,11,-10,11,-7,11,11,-8,11,-5,-2,-3,]),'ID':([0,3,5,6,7,8,9,10,11,12,13,],[4,4,4,4,4,4,4,4,4,4,4,]),'$end':([1,2,4,16,17,18,19,20,21,22,23,24,25,26,27,],[0,-1,-4,-9,-13,-10,-11,-7,-12,-14,-8,-6,-5,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'EXPR':([0,3,5,6,7,8,9,10,11,12,13,],[1,14,16,17,18,19,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> EXPR","S'",1,None,None,None),
  ('EXPR -> NUMBER','EXPR',1,'p_EXPR_NUMBER','sintatico.py',31),
  ('EXPR -> ID ATTR NUMBER','EXPR',3,'p_EXPR_ID_ATTR_EXPR','sintatico.py',35),
  ('EXPR -> ID ATTR BOOL','EXPR',3,'p_EXPR_ID_ATTR_EXPR','sintatico.py',36),
  ('EXPR -> ID','EXPR',1,'p_EXPR_ID','sintatico.py',41),
  ('EXPR -> LPAREN EXPR RPAREN','EXPR',3,'p_EXPR_LPAREN_EXPR_RPAREN','sintatico.py',49),
  ('EXPR -> EXPR ATTR EXPR','EXPR',3,'p_EXPR_ATTR_EXPR','sintatico.py',53),
  ('EXPR -> EXPR PLUS EXPR','EXPR',3,'p_EXPR_PLUS_EXPR','sintatico.py',57),
  ('EXPR -> EXPR MINUS EXPR','EXPR',3,'p_EXPR_MINUS_EXPR','sintatico.py',61),
  ('EXPR -> EXPR DIVIDE EXPR','EXPR',3,'p_EXPR_DIVIDE_EXPR','sintatico.py',65),
  ('EXPR -> EXPR TIMES EXPR','EXPR',3,'p_EXPR_TIMES_EXPR','sintatico.py',69),
  ('EXPR -> EXPR PLUSEQUAL EXPR','EXPR',3,'p_EXPR_PLUSEQUAL_EXPR','sintatico.py',73),
  ('EXPR -> EXPR EXP EXPR','EXPR',3,'p_EXPR_EXP_EXPR','sintatico.py',77),
  ('EXPR -> EXPR MINUSEQUAL EXPR','EXPR',3,'p_EXPR_MINUSEQUAL_EXPR','sintatico.py',81),
  ('EXPR -> EXPR TIMESEQUAL EXPR','EXPR',3,'p_EXPR_TIMESEQUAL_EXPR','sintatico.py',85),
  ('LID -> ID','LID',1,'p_LID','sintatico.py',89),
  ('BLOCK -> LCURLYBRACKETS CMD RCURLYBRACKETS','BLOCK',3,'p_BLOCK','sintatico.py',93),
  ('OPER -> PLUS','OPER',1,'p_OPER','sintatico.py',98),
  ('OPER -> MINUS','OPER',1,'p_OPER','sintatico.py',99),
  ('OPER -> DIVIDE','OPER',1,'p_OPER','sintatico.py',100),
  ('OPER -> TIMES','OPER',1,'p_OPER','sintatico.py',101),
  ('OPER -> LESSTHAN','OPER',1,'p_OPER','sintatico.py',102),
  ('OPER -> GREATERTHAN','OPER',1,'p_OPER','sintatico.py',103),
  ('OPER -> ATTR','OPER',1,'p_OPER','sintatico.py',104),
  ('CMD -> EXPR SEMICOLON','CMD',2,'p_CMD','sintatico.py',108),
  ('CMD -> EXPR SEMICOLON CMD','CMD',3,'p_CMD','sintatico.py',109),
  ('CMD -> empty','CMD',1,'p_CMD','sintatico.py',110),
  ('DEFINES -> DEFINE ID LPAREN LID RPAREN BLOCK','DEFINES',6,'p_DEFINES','sintatico.py',114),
  ('FORS -> FOR','FORS',1,'p_FORS','sintatico.py',118),
  ('empty -> <empty>','empty',0,'p_empty','sintatico.py',133),
]
